### ISSUE TITLE
Error evaluating expressions

### ISSUE THREAD

**Issue by micafer** [grycap/cpyutils#5]
There are problems evaluating expression with logical connectors. For example this piece of code:
```
    annie = Analyzer(autodefinevars=False)
    keywords = { 'queue': TypedClass("test", TypedClass.STRING), 'pods_free': TypedNumber(110)}
    annie.add_vars(keywords, True)
    print annie.check(' pods_free>0 && queue=="test"')
```
Returns this error:
```
Traceback (most recent call last):
  File "evaluate.py", line 663, in <module>
    print annie.check(' pods_free>0 && queue=="test"')
  File "evaluate.py", line 251, in check
    return self.yacc.parse(expr, debug=0, lexer=self.lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "evaluate.py", line 441, in p_mexp2_and
    if p[1].type != p[3].type: raise TypeError()
TypeError
```
To make it work you must add parentheses (at least to the first comp) to make it work. These two examples work:
```
    print annie.check(' (pods_free>0) && queue=="test"')
    print annie.check(' (pods_free>0) && (queue=="test")')
```

**Comment by dealfonso** [comment]
version 0.30 solves this issue
